# Generated by Django 3.1 on 2020-08-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0002_auto_20200822_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classCode',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
