# Generated by Django 3.1 on 2020-09-05 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_join_class', '0004_auto_20200822_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_of_the_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReadingMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('readingFile', models.FileField(upload_to='uploads/Reading Material/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='create_join_class.classroom')),
            ],
        ),
    ]
