# Generated by Django 3.1 on 2020-09-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0005_auto_20200905_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterials',
            name='classroom',
            field=models.ForeignKey(limit_choices_to={'teacher': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='create_join_class.classroom'),
        ),
    ]
