# Generated by Django 3.1 on 2020-09-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0007_auto_20200905_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadingMaterials',
            new_name='ReadingMaterial',
        ),
    ]
