# Generated by Django 3.1 on 2020-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0008_auto_20200905_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='readingFile',
            field=models.FileField(upload_to='uploads/ReadingMaterial/'),
        ),
    ]
