# Generated by Django 3.1 on 2020-09-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0010_readingmaterial_uploader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingMaterial',
        ),
    ]
