# Generated by Django 3.1 on 2020-09-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0012_readingmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_info', models.JSONField(null=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_join_class.readingmaterial')),
            ],
        ),
    ]
