# Generated by Django 3.1 on 2020-09-15 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_join_class', '0014_auto_20200913_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_of_the_class', to=settings.AUTH_USER_MODEL),
        ),
    ]
