# Generated by Django 3.1 on 2020-09-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0015_faceimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceImage',
        ),
    ]
