# Generated by Django 3.1 on 2020-09-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0015_auto_20200915_1334'),
        ('create_join_class', '0017_faceimage'),
    ]

    operations = [
    ]
