# Generated by Django 3.1 on 2020-09-21 06:57

import create_join_class.models
import create_join_class.validators
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0018_merge_20200921_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='imageFile',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=create_join_class.models.user_directory_path, validators=[create_join_class.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='readingFile',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='uploads/ReadingMaterial/', validators=[create_join_class.validators.validate_file_extension]),
        ),
    ]
