# Generated by Django 3.1 on 2020-09-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0019_auto_20200921_1257'),
        ('create_join_class', '0018_merge_20200918_1402'),
    ]

    operations = [
    ]
