# Generated by Django 3.1 on 2020-09-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_join_class', '0020_merge_20200925_0922'),
        ('create_join_class', '0020_merge_20200925_0834'),
    ]

    operations = [
    ]
